BEGIN;
--
-- Create model ContentType
--
CREATE TABLE "django_content_type" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(100) NOT NULL, "app_label" varchar(100) NOT NULL, "model" varchar(100) NOT NULL);
--
-- Alter unique_together for contenttype (1 constraint(s))
--
ALTER TABLE "django_content_type" ADD CONSTRAINT "django_content_type_app_label_model_76bd3d3b_uniq" UNIQUE ("app_label", "model");--
-- Create model Permission
--
CREATE TABLE "auth_permission" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(50) NOT NULL, "content_type_id" integer NOT NULL, "codename" varchar(100) NOT NULL);
--
-- Create model Group
--
CREATE TABLE "auth_group" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(80) NOT NULL UNIQUE);
CREATE TABLE "auth_group_permissions" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "group_id" integer NOT NULL, "permission_id" integer NOT NULL);
--
-- Create model User
--
CREATE TABLE "auth_user" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "password" varchar(128) NOT NULL, "last_login" timestamp with time zone NOT NULL, "is_superuser" boolean NOT NULL, "username" varchar(30) NOT NULL UNIQUE, "first_name" varchar(30) NOT NULL, "last_name" varchar(30) NOT NULL, "email" varchar(75) NOT NULL, "is_staff" boolean NOT NULL, "is_active" boolean NOT NULL, "date_joined" timestamp with time zone NOT NULL);
CREATE TABLE "auth_user_groups" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "user_id" integer NOT NULL, "group_id" integer NOT NULL);
CREATE TABLE "auth_user_user_permissions" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "user_id" integer NOT NULL, "permission_id" integer NOT NULL);
ALTER TABLE "auth_permission" ADD CONSTRAINT "auth_permission_content_type_id_codename_01ab375a_uniq" UNIQUE ("content_type_id", "codename");
ALTER TABLE "auth_permission" ADD CONSTRAINT "auth_permission_content_type_id_2f476e4b_fk_django_co" FOREIGN KEY ("content_type_id") REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "auth_permission" ("content_type_id");
CREATE INDEX "auth_group_name_a6ea08ec_like" ON "auth_group" ("name" varchar_pattern_ops);
ALTER TABLE "auth_group_permissions" ADD CONSTRAINT "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" UNIQUE ("group_id", "permission_id");
ALTER TABLE "auth_group_permissions" ADD CONSTRAINT "auth_group_permissions_group_id_b120cbf9_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "auth_group_permissions" ADD CONSTRAINT "auth_group_permissio_permission_id_84c5c92e_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "auth_group_permissions" ("group_id");
CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "auth_group_permissions" ("permission_id");
CREATE INDEX "auth_user_username_6821ab7c_like" ON "auth_user" ("username" varchar_pattern_ops);
ALTER TABLE "auth_user_groups" ADD CONSTRAINT "auth_user_groups_user_id_group_id_94350c0c_uniq" UNIQUE ("user_id", "group_id");
ALTER TABLE "auth_user_groups" ADD CONSTRAINT "auth_user_groups_user_id_6a12ed8b_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "auth_user_groups" ADD CONSTRAINT "auth_user_groups_group_id_97559544_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "auth_user_groups_user_id_6a12ed8b" ON "auth_user_groups" ("user_id");
CREATE INDEX "auth_user_groups_group_id_97559544" ON "auth_user_groups" ("group_id");
ALTER TABLE "auth_user_user_permissions" ADD CONSTRAINT "auth_user_user_permissions_user_id_permission_id_14a6b632_uniq" UNIQUE ("user_id", "permission_id");
ALTER TABLE "auth_user_user_permissions" ADD CONSTRAINT "auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "auth_user_user_permissions" ADD CONSTRAINT "auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "auth_user_user_permissions_user_id_a95ead1b" ON "auth_user_user_permissions" ("user_id");
CREATE INDEX "auth_user_user_permissions_permission_id_1fbb5f2c" ON "auth_user_user_permissions" ("permission_id");--
-- Create model LogEntry
--
CREATE TABLE "django_admin_log" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "action_time" timestamp with time zone NOT NULL, "object_id" text NULL, "object_repr" varchar(200) NOT NULL, "action_flag" smallint NOT NULL CHECK ("action_flag" >= 0), "change_message" text NOT NULL, "content_type_id" integer NULL, "user_id" integer NOT NULL);
ALTER TABLE "django_admin_log" ADD CONSTRAINT "django_admin_log_content_type_id_c4bce8eb_fk_django_co" FOREIGN KEY ("content_type_id") REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "django_admin_log" ADD CONSTRAINT "django_admin_log_user_id_c564eba6_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "django_admin_log" ("content_type_id");
CREATE INDEX "django_admin_log_user_id_c564eba6" ON "django_admin_log" ("user_id");--
-- Alter field action_time on logentry
--
-- (no-op)--
-- Alter field action_flag on logentry
--
-- (no-op)--
-- Create model Event
--
CREATE TABLE "alexie_event" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "description" varchar(100) NOT NULL, "created_in" timestamp with time zone NOT NULL, "created_by_id" integer NULL);
--
-- Create model GeneralEmotion
--
CREATE TABLE "alexie_generalemotion" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "description" varchar(50) NOT NULL, "created_in" timestamp with time zone NOT NULL, "created_by_id" integer NULL);
--
-- Create model Habit
--
CREATE TABLE "alexie_habit" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "description" varchar(50) NOT NULL, "created_in" timestamp with time zone NOT NULL, "created_by_id" integer NULL);
--
-- Create model Health
--
CREATE TABLE "alexie_health" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "description" varchar(50) NOT NULL, "created_in" timestamp with time zone NOT NULL, "created_by_id" integer NULL);
--
-- Create model MainHealth
--
CREATE TABLE "alexie_mainhealth" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "description" varchar(50) NOT NULL, "created_in" timestamp with time zone NOT NULL, "created_by_id" integer NOT NULL);
--
-- Create model MainEmotion
--
CREATE TABLE "alexie_mainemotion" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "description" varchar(50) NOT NULL, "created_in" timestamp with time zone NOT NULL, "created_by_id" integer NOT NULL);
--
-- Create model HealthLog
--
CREATE TABLE "alexie_healthlog" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_in" timestamp with time zone NOT NULL, "created_by_id" integer NOT NULL, "health_id" bigint NOT NULL);
--
-- Create model HabitLog
--
CREATE TABLE "alexie_habitlog" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_in" timestamp with time zone NOT NULL, "created_by_id" integer NOT NULL, "habit_id" bigint NOT NULL);
--
-- Create model GeneralEmotionLog
--
CREATE TABLE "alexie_generalemotionlog" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_in" timestamp with time zone NOT NULL, "created_by_id" integer NOT NULL, "emotion_id" bigint NOT NULL);
--
-- Create model EventLog
--
CREATE TABLE "alexie_eventlog" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_in" timestamp with time zone NOT NULL, "created_by_id" integer NOT NULL, "event_id" bigint NOT NULL);
ALTER TABLE "alexie_event" ADD CONSTRAINT "alexie_event_created_by_id_ff665c5f_fk_auth_user_id" FOREIGN KEY ("created_by_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "alexie_event_created_by_id_ff665c5f" ON "alexie_event" ("created_by_id");
ALTER TABLE "alexie_generalemotion" ADD CONSTRAINT "alexie_generalemotion_created_by_id_2618e762_fk_auth_user_id" FOREIGN KEY ("created_by_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "alexie_generalemotion_created_by_id_2618e762" ON "alexie_generalemotion" ("created_by_id");
ALTER TABLE "alexie_habit" ADD CONSTRAINT "alexie_habit_created_by_id_cb0254c4_fk_auth_user_id" FOREIGN KEY ("created_by_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "alexie_habit_created_by_id_cb0254c4" ON "alexie_habit" ("created_by_id");
ALTER TABLE "alexie_health" ADD CONSTRAINT "alexie_health_created_by_id_2dd10120_fk_auth_user_id" FOREIGN KEY ("created_by_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "alexie_health_created_by_id_2dd10120" ON "alexie_health" ("created_by_id");
ALTER TABLE "alexie_mainhealth" ADD CONSTRAINT "alexie_mainhealth_created_by_id_76c33dc3_fk_auth_user_id" FOREIGN KEY ("created_by_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "alexie_mainhealth_created_by_id_76c33dc3" ON "alexie_mainhealth" ("created_by_id");
ALTER TABLE "alexie_mainemotion" ADD CONSTRAINT "alexie_mainemotion_created_by_id_efac9e43_fk_auth_user_id" FOREIGN KEY ("created_by_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "alexie_mainemotion_created_by_id_efac9e43" ON "alexie_mainemotion" ("created_by_id");
ALTER TABLE "alexie_healthlog" ADD CONSTRAINT "alexie_healthlog_created_by_id_3f95dc3c_fk_auth_user_id" FOREIGN KEY ("created_by_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "alexie_healthlog" ADD CONSTRAINT "alexie_healthlog_health_id_51fb3d48_fk_alexie_health_id" FOREIGN KEY ("health_id") REFERENCES "alexie_health" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "alexie_healthlog_created_by_id_3f95dc3c" ON "alexie_healthlog" ("created_by_id");
CREATE INDEX "alexie_healthlog_health_id_51fb3d48" ON "alexie_healthlog" ("health_id");
ALTER TABLE "alexie_habitlog" ADD CONSTRAINT "alexie_habitlog_created_by_id_250f9b46_fk_auth_user_id" FOREIGN KEY ("created_by_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "alexie_habitlog" ADD CONSTRAINT "alexie_habitlog_habit_id_a1bc2d8b_fk_alexie_habit_id" FOREIGN KEY ("habit_id") REFERENCES "alexie_habit" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "alexie_habitlog_created_by_id_250f9b46" ON "alexie_habitlog" ("created_by_id");
CREATE INDEX "alexie_habitlog_habit_id_a1bc2d8b" ON "alexie_habitlog" ("habit_id");
ALTER TABLE "alexie_generalemotionlog" ADD CONSTRAINT "alexie_generalemotionlog_created_by_id_fe2a68c0_fk_auth_user_id" FOREIGN KEY ("created_by_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "alexie_generalemotionlog" ADD CONSTRAINT "alexie_generalemotio_emotion_id_3169514e_fk_alexie_ge" FOREIGN KEY ("emotion_id") REFERENCES "alexie_generalemotion" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "alexie_generalemotionlog_created_by_id_fe2a68c0" ON "alexie_generalemotionlog" ("created_by_id");
CREATE INDEX "alexie_generalemotionlog_emotion_id_3169514e" ON "alexie_generalemotionlog" ("emotion_id");
ALTER TABLE "alexie_eventlog" ADD CONSTRAINT "alexie_eventlog_created_by_id_2190685c_fk_auth_user_id" FOREIGN KEY ("created_by_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "alexie_eventlog" ADD CONSTRAINT "alexie_eventlog_event_id_f7cb0a78_fk_alexie_event_id" FOREIGN KEY ("event_id") REFERENCES "alexie_event" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "alexie_eventlog_created_by_id_2190685c" ON "alexie_eventlog" ("created_by_id");
CREATE INDEX "alexie_eventlog_event_id_f7cb0a78" ON "alexie_eventlog" ("event_id");--
-- Change Meta options on contenttype
--
-- (no-op)
--
-- Alter field name on contenttype
--
ALTER TABLE "django_content_type" ALTER COLUMN "name" DROP NOT NULL;
--
-- Raw Python operation
--
-- THIS OPERATION CANNOT BE WRITTEN AS SQL
--
-- Remove field name from contenttype
--
ALTER TABLE "django_content_type" DROP COLUMN "name" CASCADE;--
-- Alter field name on permission
--
ALTER TABLE "auth_permission" ALTER COLUMN "name" TYPE varchar(255);--
-- Alter field email on user
--
ALTER TABLE "auth_user" ALTER COLUMN "email" TYPE varchar(254);--
-- Alter field username on user
--
-- (no-op)--
-- Alter field last_login on user
--
ALTER TABLE "auth_user" ALTER COLUMN "last_login" DROP NOT NULL;--
-- Alter field username on user
--
-- (no-op)--
-- Alter field username on user
--
ALTER TABLE "auth_user" ALTER COLUMN "username" TYPE varchar(150);--
-- Alter field last_name on user
--
ALTER TABLE "auth_user" ALTER COLUMN "last_name" TYPE varchar(150);--
-- Alter field name on group
--
ALTER TABLE "auth_group" ALTER COLUMN "name" TYPE varchar(150);--
-- Raw Python operation
--
-- THIS OPERATION CANNOT BE WRITTEN AS SQL--
-- Alter field first_name on user
--
ALTER TABLE "auth_user" ALTER COLUMN "first_name" TYPE varchar(150);--
-- Create model Session
--
CREATE TABLE "django_session" ("session_key" varchar(40) NOT NULL PRIMARY KEY, "session_data" text NOT NULL, "expire_date" timestamp with time zone NOT NULL);
CREATE INDEX "django_session_session_key_c0390e0f_like" ON "django_session" ("session_key" varchar_pattern_ops);
CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" ("expire_date");
COMMIT;